name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  docs:
    name: emmylua to help doc

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Generating help
        shell: bash
        run: |
          curl -Lq https://github.com/numToStr/lemmy-help/releases/latest/download/lemmy-help-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./lemmy-help -fact \
            lua/formatlink/init.lua > doc/formatlink.txt

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(docs): auto-generate `:help` doc"
          file_pattern: doc/*.txt
