name: gendoc

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: "formatlink"
          description: "Generate arbitrary format link from URL"
          dedupsubheadings: false

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(docs): auto-generate `:help` doc"
          file_pattern: doc/*.txt
